### ISSUE TITLE
Всплывающее сообщение закрывает подпись

### ISSUE THREAD

**Issue by eoan-ermine** [Gram-ax/gramax#6]
Всплывающее сообщение "обязательный параметр" закрывает надпись и разглядеть, в какой аккаунт "Grama... что?" происходит вход невозможно. Клики по модальному окну не скрывают подсказку.

![image](https://github.com/user-attachments/assets/8250023a-f50b-4b79-bf1e-cf05b1503da9)

**Comment by DanilKazanov** [comment]
Добрый день! Это окно было временным решением, скрыли его из интерфейса.
Заявка больше не актуальна. 

Спасибо за внимательность!
